
import "../server/cron";
import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";


import { AppSidebar } from "~/components/app-sidebar";
import {
  SidebarProvider,
  SidebarInset,
} from "~/components/ui/sidebar";
import React from "react";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} dark`}>
      <body>
        <TRPCReactProvider>
          <SidebarProvider
            style={{
              "--sidebar-width": "350px",
            } as React.CSSProperties}
          >
            <AppSidebar />
            <SidebarInset>
              <div className="flex flex-1 flex-col gap-4 p-0">
                {children}
              </div>
            </SidebarInset>
          </SidebarProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
